model:
  base_learning_rate: 1.0e-05
  target: vton.model.LatentTryOnDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "inpaint"
    cond_stage_key: "image"
    image_size: 64
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 3000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        use_fp16: True
        image_size: 32 # unused
        in_channels: 18
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder
      params: 
          num_tokens: 16
          out_dims: 1024
          version: "laion/CLIP-ViT-H-14-laion2B-s32B-b79K"
    
    cond_text_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
          version: "laion/CLIP-ViT-H-14-laion2B-s32B-b79K"
          layer: "pooled"

    

data:
  target: main.DataModuleFromConfig
  params:
      batch_size: 2
      wrap: False
      train:
          target: ldm.data.vtonhdataset.VTHDDataset
          params:
              mode: train
              dataroot: datasets/mp_vton
              image_size: [512, 768]
              cloth_size: [512, 384]
      validation:
          target: ldm.data.vtonhdataset.VTHDDataset
          params:
              mode: test
              dataroot: datasets/mp_vton
              image_size: [512, 768]
              cloth_size: [512, 384]
      test:
          target: ldm.data.vtonhdataset.VTHDDataset
          params:
              mode: test
              dataroot: datasets/mp_vton
              image_size: (512, 768)
              cloth_size: (512, 384)

lightning:
  trainer:
    max_epochs: 40
    num_nodes: 1
    accelerator: 'gpu'
    gpus: "0"
    accumulate_grad_batches: 2